const ALERT = "ALERT";
const REFETCH = "REFETCH";
const REFETCH_CHAT = "REFETCH_CHAT";
const NEW_ATTACHEMENT = "NEW_ATTACHEMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const STARTTYPING = "STARTTYPING";
const STOPTYPING = "STOPTYPING";
export {
  NEW_MESSAGE,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_ATTACHEMENT,
  ALERT,
  REFETCH,
  REFETCH_CHAT,
  STARTTYPING,
  STOPTYPING,
};
