const ALERT = "ALERT";
const REFETCH = "REFETCH";
const REFETCH_CHAT = "REFETCH_CHAT";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const CREATE = "CREATE";
const NEW_ATTACHEMENT = "NEW_ATTACHEMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";

export {
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_ATTACHEMENT,
  ALERT,
  REFETCH,
  UPDATE,
  DELETE,
  CREATE,
  REFETCH_CHAT
};
